config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "books#new"

  get '/books/featured' => 'books#featured'
  
  resources :books


  # get "/books" => "books#index"
  # get "/books/new" => "books#new"
  # post "/books" => "books#create"
  # get "/books/:id" => "books#show"

  get "/users/list" => "follows#index"
  post "/follows" => "follows#create"

  post "/book_likes" => "books#like"

  get "/aws-test" => "books#aws_test"

  get '/about' => 'pages#about'








end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		if params[:liked] == 'self'
			@title = 'Your Books Profile'
			@books = current_user.books
		else
			@books = Book.all
		end
	end

	def featured
		@followees = current_user.followees
	end

	def show
		@book = Book.find_by(id: params[:id])
		@number_of_likes = @book.users.length


		# @created_at = (Time.now - @book.created_at.to_time)/1.hour

		# this method .updates @book.analysis_url if it doesn't already have a value

		if !@book.analysis_url
			analysis_url = Nlu.store_analysis(@book)
			@book.update(analysis_url: analysis_url)
			redirect_to "/books/#{@book.id}"
		else
			stats = Nlu.analysis(@book)
			@emotions_summary = stats[:emotions_summary]
			@keywords = stats[:keywords]

			@keywords.each do |keyword| # truncate extra-long keywords so they dont mess up the keyword chart
				keyword['text'] = keyword['text'].truncate(20)
			end



			blank_keyword = {
					"text": "",
					"sentiment": {
						"score": 0
					},
					"relevance": 0,
					"emotion": {
						"sadness": 0,
						"joy": 0,
						"fear": 0,
						"disgust": 0,
						"anger": 0
					}
				}



			(5 - @keywords.length).times do # if the keywords json has less than 5, add blank keywords until it has 5
				@keywords << 'none'
			end



			@score = @emotions_summary['sentiment'].round(2)
			
			if @score < -0.30 
				@sentiment_word = 'Negative'
			elsif -0.30 <= @score && @score < -0.10
				@sentiment_word = 'Fairly negative'
			elsif -0.10 <= @score && @score < -0.07
				@sentiment_word = 'Slightly negative'
			elsif -0.07 <= @score && @score < 0.07
				@sentiment_word = 'Neutral'
			elsif 0.07 <= @score && @score < 0.10
				@sentiment_word = 'Slightly positive'
			elsif 0.10 <= @score && @score < 0.30
				@sentiment_word = 'Fairly positive'
			elsif @score >= 0.30
				@sentiment_word = 'Positive'
			end
		end

		if current_user
			@like_button = true
		else
			@like_button = false
		end


		
	end

	def new
	end

	def create
		
		# validations 
		# checks if there is a file or url present. uses hidden_field_tag :form_identifier in new.html.erb
		if params[:form_identifier] == "url"
			puts "Conditional URL identifier"
			if (params[:reddit_username] == "" && params[:twitter_username] == "")
				if params[:url] == ""
					puts "URL isnt here"
					flash[:danger] = "Please pick 1 url or username"
					redirect_to "/books/new"
					return
				end
			else
				if (params[:reddit_username] == "" && params[:twitter_username] == "")
					puts "username isnt here"
					flash[:danger] = "Please give 1 username or url"
					redirect_to "/books/new"
					return
				end
			end
		elsif params[:form_identifier] == "file"
			puts "Conditional File identifier"
			if params[:file] == nil
				puts "File not there"
				flash[:danger] = "Please choose 1 url, file or username"
				redirect_to "/books/new"
				return
			end
		end

		begin
			if params[:file] && params[:title] == "" # check for title. if there isn't one, make one.
				params[:title] = File.basename(params[:file].original_filename, '.txt').parameterize('_')
			elsif params[:url] && params[:url] != "" && params[:title] == "" # url was given
				if params[:url].starts_with?("https://www.reddit.com") || (params[:url].starts_with?("www.reddit.com") && params[:url].include?("/comments/"))
					webpage = Nokogiri::HTML(
						open(
							params[:url],
							"User-Agent" => "OpenBooks"
						) 
					)
					params[:title] = webpage.at('title').inner_text
				else
					begin
						webpage = Nokogiri::HTML(open params[:url])
						params[:title] = webpage.at('title').inner_text
					rescue
						flash[:error] = "The URL didn't give a response."
						redirect_to "/"
						return
					end
				end
			elsif params[:url] == "" && (params[:reddit_username] != "" || params[:twitter_username] != "")
				params[:title] = '/u/' + params[:reddit_username] if params[:reddit_username] != ""
				params[:title] = '@' + params[:twitter_username] if params[:twitter_username] != ""
			end
		rescue
			flash[:error] = "The title or URL was not acceptable"
			redirect_to "/"
			return
		end



		params[:card_title] = params[:title].truncate(27)



		if params[:file] # this means that a file was uploaded

			begin
				book_url = Book.s3_text_upload(params) # takes in params, stores text as s3 obj, returns a url for the obj
			rescue
				flash[:error] = "Upload failed."
				redirect_to "/"
				return
			end

			begin
				@book = Book.new(title: params[:title], card_title: params[:card_title], url: book_url)
				@book.save # save the book so it has an id when we pass it to the wordcount json builder

				book_json_url = Book.s3_text_upload_json(@book)

				@book.update(book_cloud_url: book_json_url)
			rescue
				flash[:error] = "The analysis failed for this text."
				redirect_to "/"
				return
			end

		elsif params[:url] && params[:url] != "" # this means that a webpage url was given

			begin
				title = params[:title]
				url = params[:url]
				fixed_url = Book.fix_url(url)

				@book = Book.new(title: title, card_title: params[:card_title], url: fixed_url)
				@book.save

				attributes = Book.s3_web_content_json(@book)

				@book.update(
					book_cloud_url: attributes[:book_cloud_url],
					scraped_content_url: attributes[:scraped_content_url]
				)
			rescue
				flash[:error] = "URL wordgrab failed."
				redirect_to "/"
				return
			end
		elsif params[:url] == "" # this means a reddit or twitter username was given
			if params[:twitter_username] != "" && params[:reddit_username] == ""

				begin 
					title = params[:title]
					twitter_username = params[:twitter_username]
					url = 'https://twitter.com/' + twitter_username
					@book = Book.new(
						title: title, 
						card_title: params[:card_title], 
						twitter_username: twitter_username
					)
					@book.save

					attributes = Book.s3_web_content_json(@book)

					@book.update(
						url: url,
						book_cloud_url: attributes[:book_cloud_url],
						scraped_content_url: attributes[:scraped_content_url]
					)
				rescue
					flash[:error] = "Twitter failed, probably because of a typo or the user doesn't exist."
					redirect_to "/"
					return
				end
			elsif params[:reddit_username] != "" && params[:twitter_username] == ""

				begin
					title = params[:title]
					reddit_username = params[:reddit_username]
					url = 'https://reddit.com/u/' + reddit_username
					@book = Book.new(
						title: title, 
						card_title: params[:card_title], 
						reddit_username: reddit_username)

					if @book.save
						puts 'Book got saved'
					end

					attributes = Book.s3_web_content_json(@book)

					@book.update(
						url: url,
						book_cloud_url: attributes[:book_cloud_url],
						scraped_content_url: attributes[:scraped_content_url]
					)
				rescue
					flash[:error] = "Reddit failed, probably because of a typo or the user doesn't exist."
					redirect_to "/"
					return
				end
			end
		end # end if statement
		
		if @book.save
			redirect_to "/books/#{@book.id}", success: 'File successfully uploaded'
		else
			flash.now[:notice] = 'There was an error'
			redirect_to "/books/new"
		end

	end

	

	def like
		book_id = params[:book_id]
		user_id = current_user.id

		puts "*" * 100
		puts params[:book_id]
		puts current_user.id
		puts "*" * 100

		# if current_user
		# 	begin
				if !BookLike.find_by(book_id: book_id, user_id: user_id)
					@book_like = BookLike.new(book_id: book_id, user_id: user_id)
					@book_like.save(book_id: book_id, user_id: user_id)
				end
		# 	rescue
		# 		p 'error'
		# 		flash[:error] = "You can't like books unless you are logged in."
		# 	end
		# end

	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/featured.html.erb
<div class="index-header-box">
	<h1>Featured wordclouds</h1>
</div>

	<div class="col-md-12" style="margin-bottom: 100px;">
		<% @followees.each do |followee| %>

			<% if followee.books.length > 0 %>

				<div class="index-header-box">
					<h4><%= followee.email %> liked:</h4>
				</div>

				<% followee.books.each_slice(3) do |three_books| %>
					<div class="row">
						<% three_books.each do |book| %>

							<div class="col-md-4">
									<!--Card-->
									<div class="card card-block book-card" style="margin-top: 0px;">
									    <!--Card content-->
									    <div>
									        <!--Title-->
									        <h4 class="card-title book-title"><a href="<%= book.url %>"><%= book.card_title %></a></h4>
									        <!--Text-->
									        <!-- <p class="card-text"></p> -->
									        <!-- <a href="/books/<%= book.id %>" class="btn btn-primary btn-lg">WORDCLOUD</a> -->
									        <%= form_tag "/books/#{book.id}", style:"display: inline-block; padding-top: 15px;", method: :get do %>
														<button type="submit" class="btn btn-lime book-button-long">WORDCLOUD</button>
									        <% end %>
									        <%= form_tag "/book_likes", style:"display: inline-block; padding-top: 15px;", method: :post do %>
														<input type="hidden" name="book_id" value="<%= book.id %>">
														<button type="submit" class="btn btn-danger book-button-short">LIKE</button>
													<% end %>

									        <!-- <a href="#" class="btn btn-primary">LIKE</a> -->
									    </div>
									    <!--/.Card content-->

									</div>
									<!--/.Card-->
							</div>

						<% end %>

					</div>

				<% end %>
			<% end %> <!-- end 'if followee.books' conditional -->
		<% end %>
	</div>

app/views/books/index.html.erb
<div class="index-header-box">
	<% if @title %>
		<h1><%= @title %></h1>
	<% else %>
		<h1>Books &amp; wordclouds</h1>
	<% end %>

</div>

<div class="" style="margin-bottom: 100px;">
	<% @books.each_slice(3) do |three_books| %>
		<div class="row">
			<% three_books.each do |book| %>

				<div class="col-md-4">
						<!--Card-->
						<div class="card card-block book-card" style="margin-top: 0px;">
						    <!--Card content-->
						    <div>
						        <!--Title-->
						        <h4 class="card-title book-title"><a href="<%= book.url %>"><%= book.card_title %></a></h4>
						        <!--Text-->
						        <!-- <p class="card-text"></p> -->
						        <!-- <a href="/books/<%= book.id %>" class="btn btn-primary btn-lg">WORDCLOUD</a> -->
						        <%= form_tag "/books/#{book.id}", style:"display: inline-block; padding-top: 15px;", method: :get do %>
											<button type="submit" class="btn btn-lime book-button-long">WORDCLOUD</button>
						        <% end %>
						        <%= form_tag "/book_likes", style:"display: inline-block; padding-top: 15px;", method: :post do %>
											<input type="hidden" name="book_id" value="<%= book.id %>">
											<button type="submit" class="btn btn-primary book-button-short like-button">
												<i class="fa fa-thumbs-o-up prefix" aria-hidden="true"></i> LIKE
											</button>
										<% end %>

						        <!-- <a href="#" class="btn btn-primary">LIKE</a> -->
						    </div>
						    <!--/.Card content-->

						</div>
						<!--/.Card-->
				</div>

			<% end %>

		</div>

	<% end %>
</div>

app/views/books/new.html.erb
<div class="new-book-header-box">
	<h1>Create a new wordcloud</h1>
</div>

<div class="book-new-row" style="padding-top: 10px; padding-bottom: 40px;">
		<div class="col-md-5 book-new-column">
			<div class="card">
			    <div class="card-block book-upload-card">
			        <!--Header-->
			        <div class="text-center">
			            <h3><i class=""></i>Upload text</h3>
			            <hr class="mt-2 mb-2">

			            <%= form_tag books_path, enctype: 'multipart/form-data' do %>

			            	<div class="md-form book-upload-md-form">
			            		<%= hidden_field_tag "form_identifier", "file" %>
											<!-- <input type="text" name="title" placeholder="Title"><br /> -->
											<i class="fa fa-edit prefix" style="color: #a5a5a5" aria-hidden="true"></i>
											<input type="text" name="title" id="file-title-form" class="">
											<label for="file-title-form">Title</label>
										</div>
											
										<div class="hidden-file-div">
											<input type="file" name="file" class="hidden-file" id="choose-file" value="hidden file button">
										</div>

										<button type="button" class="btn btn-default" id="activate-file-choose">Choose a file</button>
										<button type="submit" class="btn btn-lime">Go!</button>

									<% end %>
			        </div>
			    </div>
			    <!--Footer-->
			</div>
			<!--/Form without header-->
		</div>
	</div>
<!-- </section> -->

<!-- <section style="padding-bottom: 0px;"> -->
	<div class="book-new-row" style="">
		<div class="col-md-5 book-new-column">
			<div class="card">
			    <div class="card-block book-url-card">
			        <!--Header-->
			        <div class="text-center">
			            <h3><i class=""></i>Online</h3>
			            <hr class="mt-2 mb-2">

			            <%= form_tag "/books", method: :post do %>
				            <%= hidden_field_tag "form_identifier", "url" %>
			            	<div class="md-form book-url-md-form">
											<i class="fa fa-edit prefix" style="color: #a5a5a5" aria-hidden="true"></i>
											<input type="text" name="title" id="title-form" class="">
											<label for="title-form">Title</label>
										</div>


										<div class="md-form book-url-md-form">
											<i class="fa fa-at prefix" style="color: #a5a5a5"  aria-hidden="true"></i>
											<input type="text" name="url" id="url-form" class="">
											<label for="url-form">URL</label>
										</div>

										<div style="padding-top: 8px;">
											<h3 style="color: #b7b7b7;">By name</h3>
										</div>

				            <div class="md-form book-url-md-form">
											<i class="fa fa-reddit-alien prefix" style="color: #e5e3e3;" aria-hidden="true"></i>
											<input type="text" name="reddit_username" id="reddit-form" class="">
											<label for="reddit-form">reddit</label>
										</div>

										<div class="md-form book-url-md-form">
											<i class="fa fa-twitter prefix" style="color: #758cff;" aria-hidden="true"></i>
											<input type="text" name="twitter_username" id="twitter-form" class="">
											<label for="twitter-form">twitter</label>
										</div>

										<button type="submit" class="btn btn-lime" style="margin-top: 40px;">Go!</button>
									<% end %>
			        </div>
			    </div>
			    <!--Footer-->
			</div>
			<!--/Form without header-->
		</div>
	</div>

	


<!-- trigger the file chooser -->
<script type="text/javascript">
	$("#activate-file-choose").click(function() {
    $("#choose-file").click();
    console.log("activated");
	})
</script>

app/views/books/show.html.erb
<head>
    <title><%= @book.title %></title>
    <script src="<%= @book.book_cloud_url %>"></script>
    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js'></script> -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.min.js'></script>
    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js'></script> -->

    
    <!-- <script src="https://s3-us-west-1.amazonaws.com/projectgutenbergtest/book_clouds/pride_and_prejudice.js"></script> -->
</head>



    <!-- <div class="example_div"></div> tooltip div -->

<script type="text/javascript">
  // var tooltip = d3.select("body")
  //   .append("div")
  //   .style("position", "absolute")
  //   .style("z-index", "10")
  //   .style("visibility", "hidden")
  //   .text("a simple tooltip");
    
  // var sampleSVG = d3.select(".example_div")
  //   .append("svg:svg")
  //   .attr("class", "sample")
  //   .attr("width", 300)
  //   .attr("height", 300);    
    
  // d3.select(".example_div svg")
  //   .append("svg:circle")
  //   .attr("stroke", "black")
  //   .attr("fill", "aliceblue")
  //   .attr("r", 50)
  //   .attr("cx", 52)
  //   .attr("cy", 52)
  //   .on("mouseover", function(){return tooltip.style("visibility", "visible");})
  //   .on("mousemove", function(){return tooltip.style("top", (event.pageY-10)+"px").style("left",(event.pageX+10)+"px");})
  //   .on("mouseout", function(){return tooltip.style("visibility", "hidden");});
</script>


<div class='row wordcloud-row'>
  <div class='col-lg-12'>
    <div class='card header-card' style="">
      <h4>
        <a class="header-link" href="<%= @book.url %>"><%= @book.title %></a>
        <div class="header-subsection-divider hidden-lg-down">
          |
        </div>
        <div class="header-subsection">
          wordcloud
        </div>
      </h4>
    </div>
    <div class="card-block wordcloud-card" id="wordcloud" style="margin-top: 0px;"></div>
  </div>
</div>


<div class='row' style="margin-top: 100px;">
  <div class='col-md-12'>
    <div class="card header-card" style=""> <!-- stats header-->
      <h4>
        <a class="header-link" href="<%= @book.url %>"><%= @book.title %></a>
          <div class="header-subsection-divider hidden-lg-down">
            |
          </div>
          <div class="header-subsection">
            stats
          </div>
      </h4>
    </div> <!-- end stats header -->

    <div class='card-block stats-card'>
      <div class='row stats-row'>
        <div class='col-md-4 stats-column stats-column-first'>
          <div class='stats-doughnut-chart-container'>
            <h4>Emotional Summary</h4>
            <div class='stats-doughnut-chart'>
              <canvas id='myDoughnutChart' style=""></canvas>
            </div>
          </div>
        </div>


        <div class='col-md-4 stats-column'>
          <div class="stats-bar-chart-container">
            <h4>Sentiment Analysis</h4>
            <div class='stats-bar-chart'>
              <canvas id='myBarChart' height="250"></canvas>

              <%= @sentiment_word %>
            </div>
          </div>
        </div>

        <div class='col-md-4 stats-column'>
          <div class='stats-key-phrases-container'>
            <h4>Top 5 Keywords</h4>
            <div class='stats-key-phrases'>
              <canvas id="myHorizontalBar" width="800" height="450"></canvas>
            </div>
          </div>
        </div>

      </div>

      <div class='row footer-row'>
        <div class='col-md-12' style='text-align: left;'>
          <!-- <div class='stats-footer-container'>
            <h4>Created: <%= @created_at %> </h4>
          </div> -->

          <div class='stats-footer-container-first'>
            <h4><a href='<%= @book.analysis_url %>' target='_blank'>Stats details</a></h4>
          </div>

          <div class='stats-footer-container'>
            <h4>Number of likes: <%= @number_of_likes %></h4>
          </div>

          <div class='stats-like-button'>
            <% if @like_button %>
              <%= form_tag "/book_likes", style:"", method: :post do %>
                <input type="hidden" name="book_id" value="<%= @book.id %>">
                <button type="submit" class="btn btn-primary book-button-short like-button">
                  <i class="fa fa-thumbs-o-up prefix" aria-hidden="true"></i>  LIKE
                </button>
              <% end %>
            <% elsif @already_liked %>
              <div class='stats-footer-container'>
                <h5>You already liked this book.</h5>
              </div>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

    







    


<script>
  d3.wordcloud()
    .size([1180, 420])
    .spiral('archimedean')
    .scale('sqrt')
    .font('Lucida-Sans-Unicode')
    .fill(d3.scale.ordinal().range(["#00770c", "#0e661e", "#048c1c", "#1ebc3a", "#40ce59", "#1fb72e"])) // green
    // .fill(d3.scale.ordinal().range(["#020202", "#2d2d2d", "#545454", "#7a7a7a", "#9e9e9e", "#aaaaaa"])) // grayscale
    // .fill(d3.scale.ordinal().range(["#080063", "#180e87", "#2a1eb2", "#4236c4", "#5e53d1", "#8d83f7"])) // blue
    // .fill(d3.scale.ordinal().range(["#4016fc", "#e2122d", "#136300", "#ad42f4", "#f77810", "#fc077d"])) // rainbow
    .words(words)
    .onwordclick(function(d, i) {
      d3.tip().show();
    })
    .start();
</script>



<script>
  var ctx = document.getElementById("myDoughnutChart").getContext('2d');
  var myDoughnutChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: [
        "joy", 
        "fear", 
        "anger",
        "disgust", 
        "sadness"
      ],
      datasets: [{
        backgroundColor: [

          "#f1c40f",
          "#3498db",
          "#e8b796",
          "#9b59b6",
          "#858796"
        ],
        data: [
          <%= @emotions_summary['joy'] %>, 
          <%= @emotions_summary['fear'] %>, 
          <%= @emotions_summary['anger'] %>,
          <%= @emotions_summary['disgust'] %>, 
          <%= @emotions_summary['sadness'] %> 
        ]
      }],
      options: {
        responsive: true,
        legend: {
            display: false
         }
      }
    }
  });
</script>

<script>
  var data = {
    labels: ["Sentiment"],
    datasets: [
        {
            label: "Average sentiment",
            fillColor: "rgba(51,71,135,0.5)",
            strokeColor: "rgba(51,71,135,0.8)",
            highlightFill: "rgba(51,71,135,0.75)",
            highlightStroke: "rgba(51,71,135,1)",
            data: [<%= @emotions_summary['sentiment'] %>]
        }
    ]
  };

  var options = {
      scaleBeginAtZero: false,
      responsive: true
  };

  var ctx2 = document.getElementById("myBarChart").getContext("2d");
  var myBarChart = Chart.Bar(ctx2, {
    data: data,
    options: options
  });
</script>

<script>
  var myHorizontalBar = new Chart(document.getElementById("myHorizontalBar"), {
      type: 'horizontalBar',
      data: {
        labels: [
          '<%= @keywords[0]['text'] %>', 
          '<%= @keywords[1]['text'] %>', 
          '<%= @keywords[2]['text'] %>', 
          '<%= @keywords[3]['text'] %>', 
          '<%= @keywords[4]['text'] %>'
        ],
        datasets: [
          {
            label: "Relevance",
            backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
            data: [
              <%= @keywords[0]['relevance'] %>, 
              <%= @keywords[1]['relevance'] %>, 
              <%= @keywords[2]['relevance'] %>, 
              <%= @keywords[3]['relevance'] %>, 
              <%= @keywords[4]['relevance'] %>
            ]
          }
        ]
      },
      options: {
        legend: { display: false },
        title: {
          display: true,
          text: ''
        }
      }
  });
</script>